FROM node:alpine

WORKDIR /app

ADD package.json package-lock.json ./

RUN npm install

ADD eslint.config.js /app/eslint.config.js
ADD .prettierrc.json /app/.prettierrc.json
ADD index.html /app/index.html
ADD vite.config.js /app/vite.config.js
ADD vitest.config.js /app/vitest.config.js

ADD src /app/src
ADD public /app/public
ADD .env.production /app/.env.production

RUN npm run build

CMD [ "sh", "-c", "npm run preview -- --host 0.0.0.0 --port ${PORT:-5173}" ]