services:
  api:
    image: karalog-api
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    volumes:
      - ./backend/src:/app/src
    env_file:
      - backend/.env
    environment:
      #- MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/karalog
      - MONGODB_CONNECTION_STRING=mongodb+srv://akinkaradag_db_user:6bsZeBfaDh2A6tjm@cluster0.bgbtatx.mongodb.net/karalog?appName=Cluster0

  frontend:
    image: karalog-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - frontend/.env
    ports:
      - '5173:5173'
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    attach: false
